# Generated by Django 4.1.6 on 2023-03-01 18:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message="Item name has to be entered in the format: 'Apple'.", regex='^[A-Z][a-z]+')])),
                ('price', models.FloatField(validators=[django.core.validators.RegexValidator(message="Price has to be entered in the format: '25.55'.", regex='^\\d+([., ]?(\\d){2}?)?$')])),
                ('currency', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Currency has to be entered in the format: 'UAH'.", regex='^[A-Z]+$')])),
                ('basic_unit', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Basic unit has to be entered in the format: 'kg'.", regex='^[A-Z][a-z].+$')])),
                ('amount_in_stock', models.IntegerField()),
                ('barcode', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="Barcode has to be entered in the format: '1234567'.", regex='^\\d{7}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
