# Generated by Django 4.1.6 on 2023-03-04 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Barcode has to be entered in the format: '1234567'.", regex='^\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='basic_unit',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Basic unit has to be entered in the format: 'kg'.", regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(validators=[django.core.validators.RegexValidator(message="Price has to be entered in the format: '25.55'.", regex='^\\d+([., ]?(\\d){1,2}?)?$')]),
        ),
    ]
