# Generated by Django 4.1.6 on 2023-03-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_barcode_alter_item_basic_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_unit', models.CharField(max_length=20)),
                ('conversion_factor', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_units', to='items.item')),
            ],
        ),
    ]
