# Generated by Django 4.1.6 on 2023-03-08 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_additionalunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalunit',
            name='additional_unit',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message="Basic unit has to be entered in the format: 'kg'.", regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='basic_unit',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Basic unit has to be entered in the format: 'kg'.", regex='^[a-zA-Z]+$')]),
        ),
    ]
