# Generated by Django 4.1.6 on 2023-03-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_additionalunit_additional_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalunit',
            old_name='additional_unit',
            new_name='additional_unit_name',
        ),
        migrations.RenameField(
            model_name='additionalunit',
            old_name='conversion_factor',
            new_name='quantity',
        ),
    ]
