# Generated by Django 4.1.5 on 2023-03-31 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_additionalunit_additional_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalunit',
            name='additional_unit_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message="Basic unit has to be entered in the format: 'kg' or 'kg.'", regex='^[a-zа-яіїєґA-ZA-ЯІЇЄҐ]+\\.?$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='basic_unit',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Basic unit has to be entered in the format: 'kg' or 'kg.'", regex='^[a-zа-яіїєґA-ZA-ЯІЇЄҐ]+\\.?$')]),
        ),
    ]
