# Generated by Django 4.1.5 on 2023-04-11 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_additionalunit_additional_unit_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(message="Item name has to be entered in the format: 'Apple'.", regex='^("?[A-Za-zА-Яа-яІіЇїЄєҐґ][a-zа-яіїєґ"‘\'ʼ.’\\u0027\\\\U+02BC\']+)(?:\\s("?[A-Za-zА-Яа-яІіЇїЄєҐґ][a-zа-яіїєґ"‘ʼ\'.’\\u0027\\\\U+02BC\']+))*$')]),
        ),
    ]
