# Generated by Django 4.1.6 on 2023-03-03 18:19

from django.db import migrations, models
from django.core.validators import RegexValidator

def remove_duplicate_emails(apps, schema_editor):
    Client = apps.get_model('yourappname', 'Client')
    duplicates = (
        Client.objects.values('email')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )
    for duplicate in duplicates:
        email = duplicate['email']
        clients = Client.objects.filter(email=email)
        clients.exclude(pk=clients.first().pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Client',
            name='email',
            field=models.EmailField(max_length=35, validators=[
        RegexValidator(regex=r'^[a-zA-Z0-9.]{3,20}@(?:[a-zA-Z0-9]{2,20}\.){1,30}[a-zA-Z]{2,10}$')]),
        ),
    ]
