# Generated by Django 4.1.6 on 2023-03-07 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(regex="^([a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]+(?:. |-|.| |\\'|\\'|’|‘|ʼ|′|))*[a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]*$")]),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex="^([a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]+(?:. |-|.| |\\'|\\'|’|‘|ʼ|′|))*[a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]*$")]),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex="^([a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]+(?:. |-|.| |\\'|\\'|’|‘|ʼ|′|))*[a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]*$")]),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\u0080-\\u024F\\u0400-\\u04FF’ʼ′\\-\\.\\| |]+')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\u0080-\\u024F\\u0400-\\u04FF’ʼ′\\-\\.\\| |]+')]),
        ),
    ]
