# Generated by Django 4.1.5 on 2023-04-03 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_address_alter_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='debt',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator(message="Amount has to be entered in the format: '25.55'.", regex='^\\d+([., ]?(\\d){1,2}?)?$')]),
        ),
    ]
