# Generated by Django 4.1.2 on 2023-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='invoices.ordereditem'),
        ),
    ]
