# Generated by Django 4.1.2 on 2023-03-15 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_ordereditem_invoice_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.RegexValidator(message="Amount has to be entered in the format: '25.55'.", regex='^\\d+([., ]?(\\d){1,2}?)?$')]),
        ),
    ]
