# Generated by Django 4.1.6 on 2023-04-04 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoice_items_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(message="Currency has to be entered in the format: 'UAH'.", regex='^[A-Z]+$')]),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='price',
            field=models.FloatField(default=True, validators=[django.core.validators.RegexValidator(message="Amount has to be entered in the format: '25.55'.", regex='^\\d+([., ]?(\\d){1,2}?)?$')]),
        ),
    ]
