# Generated by Django 4.1.6 on 2023-03-27 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(regex='^[#./0-9a-zA-Z\\s,-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Z][a-z]+')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Z][a-z]+')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Z][a-z]+')]),
        ),
    ]
