# Generated by Django 4.1.6 on 2023-04-07 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_address_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]+(?:. |-|.| |’|‘|ʼ|′|))*[a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]+(?:. |-|.| |’|‘|ʼ|′|))*[a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\u0080-\\u024F\\u0400-\\u04FF’ʼ′\\-\\.\\| |]+')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=35, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]+(?:. |-|.| |’|‘|ʼ|′|))*[a-zA-Z\\u0080-\\u024F\\u0400-\\u04FF0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\u0080-\\u024F\\u0400-\\u04FF’ʼ′\\-\\.\\| |]+')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=35, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z\\u0080-\\u024F\\u0400-\\u04FF’ʼ′\\-\\.\\| |]+')]),
        ),
    ]
